require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InvoicesController do
  render_views
  
  before(:each) do 
    User.all.each { |u| u.destroy }
  end

  describe "GET index" do
    
    describe "as a non-admin user" do
       before(:each) do
         @user = Factory(:user)
         @other_user = Factory(:user, :email => "otheruser@email.com")
       end

       it "should protect the page" do
         test_sign_in(@user)
         get 'index', :user_id => @other_user
         response.should redirect_to(root_path)
       end
    end
    
    describe "as a non-logged in user" do 
      it "should protect the page" do 
        @user = Factory(:user)
        get 'index', :user_id => @user
        response.should redirect_to(signin_path)
      end
    end
    
    describe "as an admin user" do 
      before(:each) do
        @user = Factory(:user)
        @user.toggle!(:admin)
        @user = test_sign_in(@user)
        @other_user = Factory(:user, :email => "otheruser@gmail.com")
        @order_list = Factory(:order_list, :user => @user)
      end

      it "should be successful" do
        get :index, :user_id => @other_user
        response.should be_success
      end
      
    end
    
    describe "as an owner user" do 
       before(:each) do
         @user = Factory(:user)
         @seller = Factory(:user, :email => "seller@seller.org")
         @seller = test_sign_in(@seller)
         @order_lists = Factory(:order_list, :user => @user)
       end

       it "should be successful" do
         get :index, :user_id => @seller.id
         response.should be_success
       end
     end

  end
  
  
  describe "GET 'show'" do
    describe "for owner users" do
      before(:each) do
        @user = Factory(:user)
        @seller = Factory(:user, :email => "seller1@seller.org")
        @seller = test_sign_in(@seller)
        @order_list = Factory(:order_list, :user => @user)
        @invoice = Factory(:invoice, :user => @seller, :order_list => @order_list)
      end

      it "should be successful" do
        get :show, :id => @invoice, :user_id => @seller.id
        response.should be_success
      end

      it "should find the right invoice" do
        get :show, :id => @invoice, :user_id => @seller.id
        assigns(:invoice).should == @invoice
      end

    end
    
    describe "for non-logged in users" do 
      it "should protect the page" do 
        @user = Factory(:user)
        @order_list = Factory(:order_list, :user => @user)
        @invoice = Factory(:invoice, :order_list => @order_list, :user => @user)
        get :show, :id => @invoice, :user_id => @user.id
        response.should redirect_to(signin_path)
      end
    end
    
    describe "for non-owner users" do 
      it "should protect the page" do 
        @user = Factory(:user)
        @seller = Factory(:user, :email => "seller2@seller.com")
        @seller = test_sign_in(@seller)
        @order_list = Factory(:order_list, :user => @user)
        @invoice = Factory(:invoice, :order_list => @order_list, :user => @seller)
        get :show, :id => @invoice, :user_id => @user.id
        response.should redirect_to(root_path)
      end
    end
     
  end


end
