require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OrderListingsController do
  render_views

  describe "GET index" do
    
    describe "as a non-admin user" do
       before(:each) do
         @user = Factory(:user)
         @order_list = Factory(:order_list, :user => @user)
       end

       it "should protect the page" do
         test_sign_in(@user)
         get 'index', :order_list_id => @order_list.id
         response.should redirect_to(root_path)
       end
    end
    
    describe "as a non-logged in user" do 
      it "should protect the page" do 
        @user = Factory(:user)
        @order_list = Factory(:order_list, :user => @user)
        get 'index', :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
    
    describe "as an admin user" do 
      before(:each) do
        @user = Factory(:user)
        @user.toggle!(:admin)
        @user = test_sign_in(@user)
        @order_list = Factory(:order_list, :user => @user)
        first = Factory(:order_listing, :order_list => @order_list)
        second = Factory(:order_listing, :order_list => @order_list)
        third  = Factory(:order_listing, :order_list => @order_list)
        @order_listings = [first, second, third]
        30.times do
          @order_listings << Factory(:order_listing, :order_list => @order_list)
        end
        # @order_listings.each { |ol| orderable = Factory(:orderable, :order_listing => ol); orderable.save; ol.orderables << orderable; ol.save }
      end

      it "should be successful" do
        get :index, :order_list_id => @order_list.id
        response.should be_success
      end

      it "should have the right title" do
        get :index, :order_list_id => @order_list.id
        response.should have_selector("title", :content => "Order Listings")
      end

      # it "should have an element for each order listing" do
      #   get :index, :order_list_id => @order_list.id
      #   @order_listings[0..2].each do |order_listing|
      #     response.should have_selector("td", :content => order_listing.orderables.first.product.name)
      #   end
      # end
      
      it "should paginate orderables" do
         get :index, :order_list_id => @order_list.id
         response.should have_selector("div.pagination")
         response.should have_selector("span.disabled", :content => "Previous")
         response.should have_selector("a", :href => "/order_lists/#{@order_list.id}/order_listings?page=2",
                                            :content => "2")
         response.should have_selector("a", :href => "/order_lists/#{@order_list.id}/order_listings?page=2",
                                            :content => "Next")
      end
      
    end

  end
  
  describe "GET 'new'" do
    describe "for admin users" do 
      before(:each) do
        @user = Factory(:user)
        @user.toggle!(:admin)
        @user = test_sign_in(@user)
        @order_list = Factory(:order_list, :user => @user)
      end
      
      it "should be successful" do
        get 'new', :order_list_id => @order_list.id
        response.should be_success
      end
  
      it "should have the right title" do
        get 'new', :order_list_id => @order_list.id
        response.should have_selector("title", :content => "New Order Listing")
      end 
    end
    
    describe "for non-logged in users" do 
      it "should protect the page" do 
        @user = Factory(:user)
        @order_list = Factory(:order_list, :user => @user)
        get 'new', :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
    
    describe "for non-admin users" do 
      before(:each) do 
        @user = Factory(:user)
        @user = test_sign_in(@user)
        @order_list = Factory(:order_list, :user => @user)
      end
      
      it "should protect the page" do 
        get 'new', :order_list_id => @order_list.id
        response.should redirect_to(root_path)
      end
    end
  
  end
  
  describe "GET 'show'" do
    describe "for logged in users" do
      before(:each) do
        @user = Factory(:user)
        @user = test_sign_in(@user)
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
      end
    
      it "should be successful" do
        get :show, :id => @order_listing, :order_list_id => @order_list.id
        response.should be_success
      end
          
      it "should find the right orderable" do
        get :show, :id => @order_listing, :order_list_id => @order_list.id
        assigns(:order_listing).should == @order_listing
      end
           
      it "should have the right title" do
        get :show, :id => @order_listing, :order_list_id => @order_list.id
        response.should have_selector("title", :content => "Order Listing")
      end
    
    end
    
    describe "for non-logged in users" do 
      it "should protect the page" do 
        @user = Factory(:user)
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
        get :show, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
     
  end
  
  describe "POST 'create'" do
    
    describe "for admin users" do 
  
      describe "failure" do
  
        before(:each) do
          @user = Factory(:user)
          @user.toggle!(:admin)
          @user = test_sign_in(@user)
          @order_list = Factory(:order_list, :user => @user)
          @order_listing = Factory(:order_listing, :order_list => @order_list)
          @attr = { :quantity => nil, :order_list => @order_list, :product_family => nil}
        end
  
        it "should not create an order listing" do
          lambda do
            post :create, :order_listing => @attr, :order_list_id => @order_list.id
          end.should_not change(OrderList, :count)
        end
  
        it "should have the right title" do
          post :create, :order_listing => @attr, :order_list_id => @order_list.id
          response.should have_selector("title", :content => "New Order Listing")
        end
  
        it "should render the 'new' page" do
          post :create, :order_listing => @attr, :order_list_id => @order_list.id
          response.should render_template('new')
        end
      end
    
      describe "success" do
  
        before(:each) do
          @user = Factory(:user)
          @user.toggle!(:admin)
          @user = test_sign_in(@user)
          @order_list = Factory(:order_list, :user => @user)
          @product_family = Factory(:product_family, :name => "Peppers")
          @attr = { :order_list => @order_list, :product_family => @product_family, :quantity => 7 }
        end
  
        it "should create an order listing" do
          lambda do
            post :create, :order_listing => @attr, :order_list_id => @order_list.id
          end.should change(OrderListing, :count).by(1)
        end
  
        it "should redirect to the order listing show page" do
          post :create, :order_listing => @attr, :order_list_id => @order_list.id
          response.should redirect_to(order_list_order_listing_path(@order_list,assigns(:order_listing)))
        end  
     end
    end
    
    describe "for non-admin users" do 
      
      before(:each) do 
        @user = Factory(:user)
        @user = test_sign_in(@user)
        @product_family = Factory(:product_family, :name => "Peppers")
        @order_list = Factory(:order_list, :user => @user)
       @attr = { :product_family => @product_family, :order_list => @order_list, :quantity => 3 }
      end
      
      it "should protect the page" do 
        post :create, :order_listing => @attr, :order_list_id => @order_list.id
        response.should redirect_to(root_path)
      end
   end
   
   describe "for non-logged in users" do 
     before(:each) do 
       @user = Factory(:user)
       @order_list = Factory(:order_list, :user => @user)
       @product_family = Factory(:product_family, :name => "Peppers")
       @attr = { :product_family => @product_family, :order_list => @order_list, :quantity => 10 }
      end
      
      it "should protect the page" do 
        post :create, :order_listing => @attr, :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    
   end
    
  end
  
  describe "GET 'edit'" do
  
    describe "for admin users" do 
      before(:each) do
        @user = Factory(:user)
        @user.toggle!(:admin)
        test_sign_in(@user)
        @product = Factory(:product)
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
      end
  
      it "should be successful" do
        get :edit, :id => @order_listing, :order_list_id => @order_list.id
        response.should be_success
      end
  
      it "should have the right title" do
        get :edit, :id => @order_listing, :order_list_id => @order_list.id
        response.should have_selector("title", :content => "Edit Order Listing")
      end
    end 
    
    describe "for logged in users" do 
      before(:each) do
        @user = Factory(:user)
        test_sign_in(@user)
        @product = Factory(:product)
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
      end
      
      it "should protect the page" do 
        get :edit, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(root_path)
      end
    end
    
    describe "for non-logged in users" do 
      before(:each) do
        @user = Factory(:user)
        @product = Factory(:product)
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
      end
      
      it "should protect the page" do 
        get :edit, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
  end
  
  describe "PUT 'update'" do
  
    describe "for admin users" do 
      before(:each) do
        @user = Factory(:user)
        @user.toggle!(:admin)
        test_sign_in(@user)
      end
  
      describe "failure" do
  
        before(:each) do
          @product_family = Factory(:product_family, :name => "Peppers")
          @order_list = Factory(:order_list, :user => @user)
          @order_listing = Factory(:order_listing, :order_list => @order_list)
          @attr = {:product_family => @product_family, :order_list => @order_list, :quantity => nil}
        end
  
        it "should render the 'edit' page" do
          put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
          response.should render_template('edit')
        end
  
        it "should have the right title" do
          put :update, :id => @order_listing, :order_list_id => @order_list.id, :order_listing => @attr
          response.should have_selector("title", :content => "Edit Order Listing")
        end
  
      end
  
      describe "success" do
  
        before(:each) do
          @product_family = Factory(:product_family, :name => "Peppers")
          @order_list = Factory(:order_list, :user => @user)
          @order_listing = Factory(:order_listing, :order_list => @order_list)
          @attr = {:product_family => @product_family, :order_list => @order_list, :quantity => 5}
        end
  
        it "should change the order listing's attributes" do
          put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
          @order_listing.reload
          @order_listing.product_family.should  == @attr[:product_family]
          @order_listing.order_list.should == @attr[:order_list]
          @order_listing.quantity.should == @attr[:quantity]
        end
  
        it "should redirect to the order listing show page" do
          put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
          response.should redirect_to(order_list_order_listing_path(@order_list, @order_listing))
        end
  
        it "should have a flash message" do
          put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
          flash[:success].should =~ /updated/
        end
      end
    end
    
    describe "for non-admin users" do 
      before(:each) do
        @user = Factory(:user)
        test_sign_in(@user)
        @product_family = Factory(:product_family, :name => "Peppers")
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
        @attr = { :product_family => @product_family, :order_list => @order_list, :quantity => 5 }     
      end
      
      it "should protect the page" do 
        put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
        response.should redirect_to(root_path)
      end
    end
    
    describe "for non-logged in users" do 
      before(:each) do
        @user = Factory(:user)
        @product_family = Factory(:product_family, :name => "Peppers")
        @order_list = Factory(:order_list, :user => @user)
        @order_listing = Factory(:order_listing, :order_list => @order_list)
        @attr = { :product_family => @product_family, :order_list => @order_list, :quantity => 5 }     
      end
      
      it "should protect the page" do 
        put :update, :id => @order_listing, :order_listing => @attr, :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
  end
  
  describe "DELETE 'destroy'" do
  
    before(:each) do
      @user = Factory(:user)
      @order_list = Factory(:order_list, :user => @user)
      @order_listing = Factory(:order_listing, :order_list => @order_list)
    end
  
    describe "as a non-signed-in user" do
      it "should deny access" do
        delete :destroy, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(signin_path)
      end
    end
  
    describe "as a non-admin user" do
      it "should protect the page" do
        test_sign_in(@user)
        delete :destroy, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(root_path)
      end
    end
  
    describe "as an admin user" do
  
      before(:each) do
        admin = Factory(:user, :email => "admin@example.com", :admin => true)
        test_sign_in(admin)
      end
  
      it "should destroy the order listing" do
        lambda do
          delete :destroy, :id => @order_listing, :order_list_id => @order_list.id
        end.should change(OrderListing, :count).by(-1)
      end
  
      it "should redirect to the order listing page" do
        delete :destroy, :id => @order_listing, :order_list_id => @order_list.id
        response.should redirect_to(order_list_order_listings_path(@order_list))
      end
    end
  end
end
